name: muograph
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - pytorch
  - numpy=1.21.0
  - pandas=1.3.0
  - h5py=3.3.0
  - fastprogress=1.0.0
  - scipy=1.7.0
  - scikit-spatial
  - joblib
  - numba
  - ipykernel
  - git-lfs
  - pre-commit
  - pytest
  # - eigen  # Eigen for linear algebra operations
  # - tbb  # Intel's Threading Building Blocks for parallelism
