name: Python CI

on:
  push:
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 mypy

    - name: Run Black
      run: black --check .
      if: contains(github.event.head_commit.message, '.py')

    # - name: Run Flake8
    #   run: flake8 .
    #   if: contains(github.event.head_commit.message, '.py')

    # - name: Run Mypy
    #   run: mypy .
    #   if: contains(github.event.head_commit.message, '.py')